"""Tests for CSRF protection, HTTP client lifecycle, port defaults,
template context, and DOM security.
"""

from __future__ import annotations

import re
from pathlib import Path

from fastapi.testclient import TestClient

from opsportal.core.settings import PortalSettings
from tests.conftest import csrf_headers

# ---------------------------------------------------------------------------
# CSRF protection on mutating endpoints
# ---------------------------------------------------------------------------


class TestCSRFProtection:
    """Double-submit cookie CSRF pattern must be enforced."""

    def test_post_without_csrf_token_returns_403(self, client: TestClient) -> None:
        """GIVEN POST without X-CSRF-Token header must be rejected."""
        # First GET to obtain the cookie (middleware sets it on every response)
        client.get("/")

        """WHEN executing."""
        resp = client.post("/api/tools/nonexistent/actions/test")

        """THEN the result is correct."""
        assert resp.status_code == 403
        assert "CSRF" in resp.json().get("error", "")

    def test_post_with_wrong_csrf_token_returns_403(self, client: TestClient) -> None:
        """GIVEN POST with a wrong X-CSRF-Token must be rejected."""
        client.get("/")

        """WHEN executing."""
        resp = client.post(
            "/api/tools/nonexistent/actions/test",
            headers={"x-csrf-token": "wrong-token-value"},
        )

        """THEN the result is correct."""
        assert resp.status_code == 403

    def test_post_with_matching_csrf_token_passes(self, client: TestClient) -> None:
        """GIVEN POST with correct X-CSRF-Token passes CSRF and reaches routing."""
        hdrs = csrf_headers(client)
        # Target a non-existent tool — should get 404, NOT 403

        """WHEN executing."""
        resp = client.post(
            "/api/tools/nonexistent/actions/test",
            headers=hdrs,
        )

        """THEN the result is correct."""
        assert resp.status_code == 404

    def test_put_without_csrf_returns_403(self, client: TestClient) -> None:
        """GIVEN PUT is also a mutating method and must require CSRF."""
        client.get("/")

        """WHEN executing."""
        resp = client.put("/api/tools/x/config", content=b"{}")

        """THEN the result is correct."""
        assert resp.status_code == 403

    def test_delete_without_csrf_returns_403(self, client: TestClient) -> None:
        """GIVEN DELETE must also be protected."""
        client.get("/")

        """WHEN executing."""
        resp = client.delete("/api/tools/x/anything")

        """THEN the result is correct."""
        assert resp.status_code == 403

    def test_health_endpoint_exempt_from_csrf(self, client: TestClient) -> None:
        """GIVEN Health API endpoints must be exempt from CSRF checks."""

        """WHEN executing."""
        resp = client.get("/api/health")

        """THEN the result is correct."""
        assert resp.status_code == 200

    def test_csrf_cookie_set_on_get(self, client: TestClient) -> None:
        """GIVEN a fresh client making a GET request."""

        """WHEN executing."""
        client.get("/")

        """THEN the result is correct."""
        assert "opsportal_csrf" in client.cookies

    def test_csrf_cookie_is_64_hex_chars(self, client: TestClient) -> None:
        """GIVEN Token must be generated by secrets.token_hex(32) → 64 hex chars."""
        client.get("/")

        """WHEN executing."""
        token = client.cookies.get("opsportal_csrf", "")

        """THEN the result is correct."""
        assert re.fullmatch(r"[0-9a-f]{64}", token), f"Bad token format: {token!r}"


# ---------------------------------------------------------------------------
# Shared HTTP client for adapters
# ---------------------------------------------------------------------------


class TestSharedHTTPClient:
    """Adapters must reuse a single httpx.AsyncClient instead of creating one per call."""

    def test_releaseboard_adapter_has_http_client_attr(self) -> None:
        """GIVEN the releaseboard adapter has http client attr scenario."""
        from opsportal.adapters.releaseboard import ReleaseBoardAdapter
        from opsportal.services.process_manager import ProcessManager

        pm = ProcessManager()

        """WHEN executing."""
        adapter = ReleaseBoardAdapter(repo_path=Path("/tmp"), process_manager=pm)

        """THEN the result is correct."""
        assert hasattr(adapter, "_http_client")
        assert adapter._http_client is None

    def test_releasepilot_adapter_has_http_client_attr(self) -> None:
        """GIVEN the releasepilot adapter has http client attr scenario."""
        from opsportal.adapters.releasepilot import ReleasePilotAdapter
        from opsportal.services.process_manager import ProcessManager

        pm = ProcessManager()

        """WHEN executing."""
        adapter = ReleasePilotAdapter(repo_path=Path("/tmp"), process_manager=pm)

        """THEN the result is correct."""
        assert hasattr(adapter, "_http_client")
        assert adapter._http_client is None

    def test_get_http_client_returns_same_instance(self) -> None:
        """GIVEN the get http client returns same instance scenario."""
        from opsportal.adapters.releaseboard import ReleaseBoardAdapter
        from opsportal.services.process_manager import ProcessManager

        pm = ProcessManager()
        adapter = ReleaseBoardAdapter(repo_path=Path("/tmp"), process_manager=pm)
        c1 = adapter._get_http_client()

        """WHEN executing."""
        c2 = adapter._get_http_client()

        """THEN the result is correct."""
        assert c1 is c2


# ---------------------------------------------------------------------------
# Port default fallback from CLI to settings
# ---------------------------------------------------------------------------


class TestPortDefault:
    """CLI serve command must fall back to settings.port when --port is omitted."""

    def test_settings_port_default_is_8000(self, tmp_settings: PortalSettings) -> None:
        """GIVEN the settings port default is 8000 scenario."""

        """THEN the result is correct."""

        """WHEN executing."""
        assert tmp_settings.port == 9999  # our fixture overrides it

    def test_default_settings_port_is_8000(self, tmp_path: Path) -> None:
        """GIVEN the default settings port is 8000 scenario."""
        manifest = tmp_path / "opsportal.yaml"
        manifest.write_text("tools: {}\n")

        """WHEN executing."""
        s = PortalSettings(
            manifest_path=manifest,
            artifact_dir=tmp_path,
            work_dir=tmp_path,
            tools_base_dir=tmp_path,
        )

        """THEN the result is correct."""
        assert s.port == 8000

    def test_cli_port_none_falls_back_to_settings(self) -> None:
        """GIVEN When --port is not provided (None), settings.port is used."""
        # Inspect the serve command's default; the type annotation is now Optional
        import inspect

        import opsportal.__main__ as main_mod

        sig = inspect.signature(main_mod.serve)

        """WHEN executing."""
        port_param = sig.parameters["port"]

        """THEN the result is correct."""
        assert port_param.default is None or hasattr(port_param.default, "default")


# ---------------------------------------------------------------------------
# Process logs included in tool web template context
# ---------------------------------------------------------------------------


class TestProcLogsInTemplate:
    """The tool_web.html template context must include proc_logs."""

    def test_route_passes_proc_logs(self) -> None:
        """GIVEN Verify the route code builds ctx with proc_logs key."""
        import inspect

        from opsportal.app.routes import tool_page

        """WHEN executing."""
        src = inspect.getsource(tool_page)

        """THEN the result is correct."""
        assert "proc_logs" in src, "tool_page route must pass proc_logs to template context"


# ---------------------------------------------------------------------------
# DOM security — no innerHTML with translation strings
# ---------------------------------------------------------------------------


class TestNoInnerHTMLWithTranslations:
    """portal.js must not use innerHTML with translated strings (XSS risk)."""

    def test_no_innerhtml_in_portal_js(self) -> None:
        """GIVEN the no innerhtml in portal js scenario."""
        js_path = (
            Path(__file__).resolve().parent.parent
            / "src"
            / "opsportal"
            / "ui"
            / "static"
            / "js"
            / "portal.js"
        )

        """WHEN executing."""
        content = js_path.read_text(encoding="utf-8")
        # innerHTML should not appear at all now

        """THEN the result is correct."""
        assert "innerHTML" not in content, (
            "portal.js still contains innerHTML — use DOM APIs instead"
        )

    def test_csrf_token_helper_exists(self) -> None:
        """GIVEN portal.js must define the _csrfToken() helper."""
        js_path = (
            Path(__file__).resolve().parent.parent
            / "src"
            / "opsportal"
            / "ui"
            / "static"
            / "js"
            / "portal.js"
        )

        """WHEN executing."""
        content = js_path.read_text(encoding="utf-8")

        """THEN the result is correct."""
        assert "_csrfToken" in content
        assert "opsportal_csrf" in content

    def test_fetch_calls_include_csrf_header(self) -> None:
        """GIVEN All POST fetch() calls must include X-CSRF-Token header."""

        """WHEN executing."""
        js_path = (
            Path(__file__).resolve().parent.parent
            / "src"
            / "opsportal"
            / "ui"
            / "static"
            / "js"
            / "portal.js"
        )
        content = js_path.read_text(encoding="utf-8")
        # Every fetch with method POST should have the header
        post_blocks = re.findall(
            r'fetch\([^)]+,\s*\{[^}]*method:\s*"POST"[^}]*\}', content, re.DOTALL
        )

        """THEN the result is correct."""
        for block in post_blocks:
            assert "X-CSRF-Token" in block, f"Missing X-CSRF-Token in: {block[:100]}"
